name: Builds

on: [push, pull_request]

jobs:
  build-server:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

        seps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: '11'
          - run: ./gradlew clean
          - run: ./gradlew build
